### ISSUE TITLE
[ngUpgrade] downgrade NG2 component/provider during boostrap

### ISSUE THREAD

**Issue by aitboudad** [ngParty/ng-metadata#121]
similar ot #100 but for @angular2
```ts
import { NgMetadataUpgradeAdapter } from 'ng-metadata/upgrade';
import { UpgradeAdapter } from '@angular/upgrade';
import { App, APP_PROVIDERS } from './app.component';
import { NG2_PROVIDERS } from './ng2';

export const upgradeAdapter = new NgMetadataUpgradeAdapter( UpgradeAdapter );

upgradeAdapter.bootstrap(App, [
   APP_PROVIDERS,
   NG2_PROVIDERS
]);
```

**Comment by aciccarello** [comment]
Are you requesting that ng2 providers be downgraded automatically? 

I haven't used the [upgrade helpers](https://hotell.gitbooks.io/ng-metadata/content/docs/api/upgrade/class.html) yet but wouldn't you simply call `downgradeNg2Provider(NG2_PROVIDERS)`?

**Comment by aitboudad** [comment]
Yes I want that ng2 providers/components be downgraded automatically!

For `upgrade helpers` downgradeNg2Provider/downgradeNg2Component work only with the legacy way, which is not suitable
```js
.directive(...upgradeAdapter.downgradeNg2Component(Ng2Component))
.factory(...upgradeAdapter.downgradeNg2Provider('ng2Service', { useClass: Ng2Service }))
```

**Comment by JamesHenry** [comment]
We also have `provideNg2Provider` which can be used in any providers array (including bootstrap):

```
const DOWNGRADED_NG2_PROVIDERS = [
  upgradeAdapter.provideNg2Provider('ng2Service', { useClass: Ng2Service }),
]

upgradeAdapter.bootstrap(App, [
   APP_PROVIDERS,
   DOWNGRADED_NG2_PROVIDERS,
]);
```

**Comment by JamesHenry** [comment]
I'm going to assume this helped you. This will all be subject to change anyway because of the upcoming NgModule work

**Comment by aitboudad** [comment]
yep thanks!
