### ISSUE TITLE
resolveReflectiveProvider doesn't allow for false useValue

### ISSUE THREAD

**Issue by hspier** [ngParty/ng-metadata#123]
Given a provider declared as:

`let PROD_MODE: OpaqueToken = new OpaqueToken("PROD_MODE");
 let IS_PROD: boolean = false;
 
 @Component({
   providers: [
     {provide: PROD_MODE, useValue: IS_PROD}
   ]
})
export class AppComponent {}
...
@Injectable
export class MyService {
    constructor(@Inject(PROD_MODE) isProductionMode: boolean) {}
}
`
Results in:
Cannot read property 'method' of undefined

**Comment by aciccarello** [comment]
I'm a little confused what error you are getting. Can you replicate this in a [Plunker](https://plnkr.co/edit/7Fr7oO)?

**Comment by hspier** [comment]
See here: https://plnkr.co/edit/YEeHK3zA7L30xCAuYgks
I was able to reproduce the issue simply by defining the falsy useValue provider.

**Comment by aciccarello** [comment]
Okay, I see. Is there a reason you need to pass that as a provider instead of via an import?

**Comment by hspier** [comment]
For this particular case, it to design a multi NPM module application in which one will be defining this but would let the main module overwrite this with the actual final value.
