### ISSUE TITLE
bundle doesn't match angular.module signature

### ISSUE THREAD

**Issue by DaSchTour** [ngParty/ng-metadata#124]
Just following the example the bootstrap recipe I have the following lines
```typescript
@Component({
    selector: 'admin',
    template: '...',
})
export class AdminComponent{}

const AdminModule = bundle(AdminComponent, []);

export const AppModule = angular.module('myApp',[AdminModule]);
```
I get the following error:

> Error:(28, 49) TS2345: Argument of type 'IModule[]' is not assignable to parameter of type 'string[]'.
 Type 'IModule' is not assignable to type 'string'.

As from what I understand the bundle function already creates a module. I thought that I could insert this directly into `angular.bootstrap()` like this.

```typescript
angular.bootstrap(document, [AdminModule]);
```

But that leads to the following error
> Error:(15, 33) TS2345: Argument of type 'IModule[]' is not assignable to parameter of type '(string | Function | any[])[]'.
 Type 'IModule' is not assignable to type 'string | Function | any[]'.
 Type 'IModule' is not assignable to type 'any[]'.
 Property 'length' is missing in type 'IModule'.

So I get the impression, that there is something wrong about the documentation or about what the bundle function does or how the interface is described.

**Comment by JamesHenry** [comment]
You are right when you say that it creates a module, and so you want to take the `name` property from that module and pass it into the array:

```
const AdminModule = bundle(AdminComponent, []).name;

export const AppModule = angular.module('myApp',[AdminModule]);
```

**Comment by JamesHenry** [comment]
One thing I would add, though, is that you should really look at using ng-metadata's own bootstrap instead of `angular.bootstrap` to get you as close to possible to Angular 2 semantics

**Comment by DaSchTour** [comment]
Yes I know. But that's the next step of migration. I still have `$templateCache` and `$provide` used in `.run()` and `.config()` so I wanted to left this as it is and use `angular.module()`.

With the `.name` property (how could I have missed that) bootstraping works fine. Thanks for the fast help.

**Comment by DaSchTour** [comment]
Well, I guess you were right about using ng-metadata's bootstrap. Just moved around some parts and I don't need `angular.module` and `angular.bootstrap` and it works better than before.
BTW: Great work! Now It's a lot easier for me to work on angular 1 and angular 2 projects at the same time.
