### ISSUE TITLE
Angular 2 stable - @NgModule design

### ISSUE THREAD

**Issue by aciccarello** [ngParty/ng-metadata#126]
The big change in RC5 was the move to modules. It moves away from declaring directives and services in components to declaring them in "module files". This actually lines up well with the `angular.module` function of ng1. Here my initial idea of how this could be mapped. Any thoughts?

```TypeScript
@NgModule({
  declarations: [ AwesomePipe, HighlightDirective, TitleComponent ], // components, directives, filters
  providers: [ UserService ], // provided services
  imports: [ SharedModule, 'ngAnimate' ], // module dependencies
  exports: [ HighlightDirective, UserService, SharedModule ] // shows what is intended to be public
})
```

- **declarations** - registers components directives and pipe classes with `angular.module(...).directive()` or `.filter()`
- **providers** - registers services via `angular.module(...).service()`
- **imports** - modules to register in `angular.module(..., [dependencies])` (could be decorated module or string)
- **exports** - show what declarations are intended to be used in other modules (even though ng1 makes all declarations public)
- **bootstrap** - root component to place in dom
- **entryComponents** - not needed?

## References:
https://angularjs.blogspot.com/2016/08/angular-2-rc5-ngmodules-lazy-loading.html
https://angular.io/docs/ts/latest/guide/ngmodule.html
https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html
https://docs.angularjs.org/api/ng/function/angular.module
https://docs.angularjs.org/api/ng/type/angular.Module

**Comment by JamesHenry** [comment]
We are now working on this!

@Hotell, with regards to `exports`, `bootstrap` and `entryComponents`, do you think we should include them as properties which do nothing? Or leave them out of ng-metadata's NgModule interface?

**Pros**
- Supports the full interface for NgModule
- Allows users to configure module structure exactly how they would for Angular 2

**Cons**
- Potentially confusing
- Exports, for example, will have no affect on the availability of providers within the app, and so you could easily misconfigure it (in terms of Angular 2) and it would still work (in an Angular 1 "global everything" world)
- Bootstrap and entryComponents have no applicable meaning in Angular 1

**Comment by aciccarello** [comment]
As I think about it, I'd vote for leaving them out. People could leave a comment for themselves if they want to keep things inline with ng2. Either way the documentation should be clear.

```TypeScript
@NgModule({
  declarations: [ AwesomePipe, HighlightDirective, TitleComponent ],
  providers: [ UserService ],
  imports: [ SharedModule, 'ngAnimate' ],
  // uncomment for ng2 migration:
  // exports: [ HighlightDirective, UserService, SharedModule ]
})
```

**Comment by Hotell** [comment]
@aciccarello @JamesHenry 
I would include whole API, and explicitly state in source code docs and Markdown docs, that they don't do anything as for now ( maybe later we can provide some mechanism to emit warnings or errors when someone uses something from some feature module and didn't exported that component/directive/pipe etc... )

It will enforce the right Angular 2 architecture mindset. Leaving comments is not very good idea IMHO.

**Comment by aciccarello** [comment]
> maybe later we can provide some mechanism to emit warnings or errors when someone uses something from some feature module and didn't exported that component/directive/pipe etc..

:+1: That's a great idea. Maybe it could be a flag similar to ng1 strict dependency injection.

**Comment by DaSchTour** [comment]
I've just taken a quick look on the readme of 3.0.0-beta and wondered a bit about how ngModule and bootstraping works. It look like bootstraping of a module would bootstrap all components from a module? So why not use the bootstrap property of ngModule?
BTW: Great work! While Angular 2 misses so much features it feels like angular 1.5 + ng-metadata is the better angular 2 :D

**Comment by JamesHenry** [comment]
:+1:

Please be aware that docs have not been updated for 3 beta. I will be tackling that this weekend and then we should be good to release 3.0.0

**Comment by DaSchTour** [comment]
@JamesHenry that's why I was referring to the README, although maybe it was CHANGELOG 😉 
Either way, great to hear release of 3.0.0 is near. So maybe I can already make use of it for finishing my next project I build upon version 2 of ng-metadata.
