### ISSUE TITLE
NgForm incorrectly implements interface IFormController

### ISSUE THREAD

**Issue by aciccarello** [ngParty/ng-metadata#127]
The latest version of angular from DefinitelyTyped added a `$name` property to the `IFormController`. See DefinitelyTyped/DefinitelyTyped#10352

> ERROR in c:\Users\AC186067\Documents\Projects\ARCS\arcs-online\arcs-client\node_modules\ng-metadata\src\common\directives\ng_form.d.ts                                                              
> (1,31): error TS2420: Class 'NgForm' incorrectly implements interface 'IFormController'.                                                                                                            
>   Property '$name' is missing in type 'NgForm'.

Workaround is to use a prior version from DT. Such as the following:

```json
"globalDependencies": {
  "angular": "registry:dt/angular#1.5.0+20160627105203"
},
```

**Comment by Hotell** [comment]
can you pls submit PR with updated NgForm ?
