### ISSUE TITLE
Component and Directive selector property doesn't actually restrict by element tag or attribute

### ISSUE THREAD

**Issue by rockmacaca** [ngParty/ng-metadata#128]
Title is pretty self explanatory, so here's an example:

```
@Directive({ selector: '[some-directive]' })
export class MyDirective {
  constructor(@Inject('$element') $element) {
    console.log($element);
  }
}
```

This directive will log the creation of a controller on both `<some-directive></some-directive>` and `<div some-directive></div>` event though the query selector specified should only match attribute values. This happens vice versa for directives made with `@Component`.

I'm assuming this is not intended behavior and I'm not expected to inlcude `legacy: { restrict: 'A' }` in all my directive definitions.

**Comment by Hotell** [comment]
yes we are not restricting, it's left on Angular which is `EA` by default. I don't see a real issue with this. but it can be implemented very easily within the core.

But if somebody uses directive selector as element, that's the implementer own problem I guess, why would somebody tried to do that :)

**Comment by rockmacaca** [comment]
Haha yes, true. I actually only discovered it by accident when trying to port over ng-forward's [DOM event directives](https://github.com/ngUpgraders/ng-forward/blob/master/lib/events/events.ts) to my project when the `'input'` directive started behaving strange (matching `<input>` elements). And then that's where I ran into #129 :P

Anyway, I gave up on that and just switched everything back to `ng-${event}`.

**Comment by artaommahe** [comment]
> yes we are not restricting, it's left on Angular which is EA by default. I don't see a real issue with this. but it can be implemented very easily within the core.
I have `SmileComponent` with 'smile' selector that uses only as component. And then i created `ChatSmilesListSmileComponent` that has `@Input() smile` and i cant use it so, because of
```
Multiple directives [chatSmilesListSmile (module: ChatSmileModule), smile (module: SmileModule)] asking for new/isolated scope on: <chat-smiles-list-smile ng-repeat="smile in ::smilesGroup track by smile.code" smile="::smile" ...
```
`smile` attribute detects as `Smile` component..

**Comment by Hotell** [comment]
hmm that's valid, but it should be binded input template binding `[smile]="::smile"` which would mitigate your issue

**Comment by rockmacaca** [comment]
Can we have it so that the selector provided is actually mapped to a restriction? A case that I need is a directive on all `<video>` elements to do something when the `loadedmetadata` event fires. The selector I should use in this case would be `'video'`, not `'[video]'`, but it won't work if use `@Directive`. Angular 2 supports this use.

A workaround would be to just use `@Component` without a template, but that is illegal in Angular 2.
