### ISSUE TITLE
Directive attribute selectors can't be used as a bindable input

### ISSUE THREAD

**Issue by rockmacaca** [ngParty/ng-metadata#129]
It currently doesn't seem possible to recreate the basic [Attribute Directives example](https://angular.io/docs/ts/latest/guide/attribute-directives.html) in ng-metadata - the myHighlight directive is doubling as both the selector and input, but instead it isn't matched at all.

```
<p [myHighlight]="color">Highlight me!</p>
```
or ng-metadata equivalent
```
<p [my-highlight]="color">Highlight me!</p>
```

Instead, to get it to work the way as intended, something like the following is necessary:
```
<p my-highlight [color]="color">Highlight me!</p>
```

It _is_ possible to use an Angular expression in this case,
```
<p my-highlight="{{color}}">Highlight me!</p>
```
but often that isn't desirable.

**Comment by rockmacaca** [comment]
I'm assuming this just means that for every attribute `directive` registered, three others `[directive]`, `(directive)`, and `[(directive)]` should be created as well. I'm interested in contributing, I'm just unfamiliar with the code base and fairly new to Typescript, so it's been taking a lot of reading to event begin to understand how this project works.

**Comment by Hotell** [comment]
hey! that example is already in Playground https://github.com/ngParty/ng-metadata/tree/master/playground/app/components/attribute-directive

As you've noticed, attribute directives cannot be bound automatically via template syntax, because angular 1 compiler constraint. so Instead you can define the binding type manually within your class or just add the bindings via other attributes like in playground:

binding via other attribute:

```typescript
 @Input('color') highlightColor: string;
```
```html
<p my-highlight [color]="$ctrl.color" (on-color-click)="$ctrl.colorClicked($event)">Highlight me!</p>
```

binding via manually set binding type( not preferred )
```typescript
 @Input('<') myHighlight: string;
```
```html
<p my-highlight="$ctrl.color" (on-color-click)="$ctrl.colorClicked($event)">Highlight me!</p>
```

**Comment by Hotell** [comment]
Feel free to submit new recipe to docs, code is already ready in playground ;)

**Comment by rockmacaca** [comment]
Oooh, I forgot about that legacy syntax you've made available. I actually like that second one since it lets me keep my existing directives in one attribute (and I plan to keep them that way once I'm on Angular 2). I'll be sure to check out the rest of playground!

You seem to have considered this case already, I'll go ahead and close it. ty!
