### ISSUE TITLE
Cannot install newer version of rxjs then what is specified as peer dependency

### ISSUE THREAD

**Issue by reppners** [ngParty/ng-metadata#131]
I would like to include a newer version than rxjs@5.0.0-beta.6 but npm would not let me:

```npm ERR! peerinvalid The package rxjs@5.0.0-beta.11 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer ng-metadata@2.1.1 wants rxjs@5.0.0-beta.6```

**Comment by zagushka** [comment]
+1

**Comment by Hotell** [comment]
I'm following Angular 2 peer dependencies, because otherwise when switching to ng2 from ngMetadata you would get the same error created by RxJs version differences
