### ISSUE TITLE
How to do a [(ngModel)] for a custom component with ng-metadata ?

### ISSUE THREAD

**Issue by JulienBourgain** [ngParty/ng-metadata#138]
I think i have miss something but...
How to do a [(ngModel)] for a custom component with ng-metadata ?

like : `<my-comp [(ngModel)]="hero.name">`

In angular1, we can simply define a binding to do that :
```
angular.component('my-comp', {
    binding: {
        myVar: '=ngModel'
    }
}
```

in the component we have access to the var, and the parent component act with his child like he do with other inputs form. With that, we can use ng-change, validation, etc...

with ng-metadata i don't find the method to do that :(

thank for the help

**Comment by Hotell** [comment]
Hey! Good question.

Here is the answer:

First of all if you are propagating data via `ngModel` the way you've described, you are doing it wrong.

If you wanna propagate data always prefer one way binding.

If you need ngModel for validation etc you have to require it and then set your own `$render` and `$setViewValue` + `$validators` if needed. YMMV in this one

so it would look like something like this:

```typescript
import {NgModel} from 'ng-metadata/common';
import {Component,Self,OnInit} from 'ng-metadata/core';

@Component({
 selector:'my-foo',
 template: `<div> oh hay!</div>`
})
class MyFooComponent implements OnInit {

  // require(local Inject) attribute directive - in our case ngModel
  constructor(private @Self() ngModel: NgModel){}

  ngOnInit(){
   // do your stuff here
   this.ngModel.$render = () => { /*...*/ }
   this.ngModel.$validator.myCustomOne = () => { /* ... */ }
  }
  updateValue(){
    this.ngModel.$setViewValue('hello new world')
 }
}
```

**Comment by JulienBourgain** [comment]
And we need an event to update the parent ? 

Ok, the solution is simple thanks !

**Comment by Hotell** [comment]
no, this will update the parent:
```
updateValue(){
    this.ngModel.$setViewValue('hello new world')
 }
```

it's confusing, that's one of reasons why ngModel is kind of tricky in Angular 1

**Comment by JulienBourgain** [comment]
thank you

**Comment by jbojcic1** [comment]
@JulienBourgain whit this code what happens if ngModel changes from outside this component?

**Comment by benneq** [comment]
How can I listen for changes of ngModel? Do I have to use scope.$watch ?

**Comment by aciccarello** [comment]
@benneq What do you want to listen to your ngModel changes? Why wouldn't you just use [ngChange](https://docs.angularjs.org/api/ng/directive/ngChange)?

**Comment by benneq** [comment]
I have a @Directive which manipulates the ng-model of an input. Something like `<input my-directive ng-model="$ctrl.foo">`

MyDirective injects `@Self() ngModel: NgModel`. From within my directive I can set the controller's (or component's) `foo` value using `this.ngModel.$setViewValue(..)` and `this.ngModel.render()`.

**But** if the controller (or component) changes `foo`'s value, I'm not able to handle that value update within my directive.

Can you give me some advice?

**Comment by aciccarello** [comment]
@benneq Sorry, I haven't used the NgModelController much. Maybe look into the validator API?
https://docs.angularjs.org/api/ng/type/ngModel.NgModelController
