### ISSUE TITLE
Optional bindings support (<?, =?, &?)

### ISSUE THREAD

**Issue by reppners** [ngParty/ng-metadata#139]
I did not manage to make optional bindings work. Tried like described in #45 but that didn't work either. Also even if it would have worked I would like to avoid repeating the property name when no alias is wanted to achieve optional binding support.

Would you accept contribution adding a dedicated attribute that does not clash with ng2 to support optional bindings?

Also I did not find any notion of optional bindings in ng2. Do you have any further knowledge of why there are none in ng2? Are they regarded as an anti-pattern?

**Comment by Hotell** [comment]
Hey!, 

Optional bindings are pretty straightforward in both ngMetadata and Angular 2

```typescript
@Component({
  selector:'my-cmp',
  template: 'Hello cmp <b>{{ $ctrl.iAmOptional }}</b>'
})
class MyComponent {
  @Input() iAmRequired: string;
  // you can see by definition that this is optional because it has a default value
  @Input() iAmOptional = 'you can skip me';
}
```

```html
<my-cmp i-am-required="hello"></my-cmp>
```
should output: `Hello cmp <b>you can skip me</b>`

```html
<my-cmp i-am-required="hello" i-am-optional="indeeed"></my-cmp>
```
should output: `Hello cmp <b>indeeed</b>`


from implementation side of ngMetadata, those bindings are created always as optional, afair :)

**Comment by reppners** [comment]
nice! thx for the fast response 👍

**Comment by aciccarello** [comment]
> from implementation side of ngMetadata, those bindings are created always as optional, afair :)

:+1: This is helpful to know. Maybe it should be added to the [`@input` docs](https://hotell.gitbooks.io/ng-metadata/content/docs/api/core/decorator.html#input)

> Template bindings equivalent vs declaration bindings:
> 
> | Template       | Declaration @Input('TYPE') |
> | -------------- | -------------------------- |
> | `[(property)]` | `=?`                        |
> | `[property]`   | `<?`                        |
> | `property`     | `@?`                        |

**Comment by Hotell** [comment]
hey @aciccarello instead of posting these kinds of hints her, it would be super useful for everyone if you'd rather submit PR to docs! ;)

thanks in advance 👍

**Comment by aciccarello** [comment]
@Hotell NP, just wanted to make sure it made sense :smile:
