### ISSUE TITLE
@Component transclusion not enabled by default

### ISSUE THREAD

**Issue by reppners** [ngParty/ng-metadata#142]
Was it intentional to not activate transclusion on components by default? I was expecting it to be on by default.

I'm also using the legacy property to set the controllerAs property, but completely not specifying `legacy` did not change the result.

```ts
@Component( {
    selector: "st-action-list-item",
    templateUrl: "ActionListItem.html",
    moduleId: module.id,
    legacy: {
        controllerAs: Constants.ControllerAs,
        transclude: true // thought this would not be needed
    }
} )
```

**Comment by Hotell** [comment]
I'm following angular 1 in terms of transclusion. It's not enabled by default because only one directive/component allows transclusion, so if it will be enabled by default, there would be clashes.

**Comment by Hotell** [comment]
anyway you are saying that overriding default controllerAs: '$ctrl' to your custom name doesn't work?

Plnkr or didn't happen! :D

**Comment by reppners** [comment]
> It's not enabled by default because only one directive/component allows transclusion, so if it will be enabled by default, there would be clashes.

Good point, I did miss that! Thx for the explanation 👍 

> anyway you are saying that overriding default controllerAs: '$ctrl' to your custom name doesn't work?

Hehe, no worries it works as expected. I just mentioned it in case it would have been a side effect if I used the legacy object. Although I had to get rid of the controllerAs override because otherwise WebStorm 2016.3 would fail to provide autocompletion and code highlighting in the template..
