### ISSUE TITLE
@ViewChild issue

### ISSUE THREAD

**Issue by hspier** [ngParty/ng-metadata#157]
When using @ViewChild with a component class, I end up with an undefined variable because the child component controller is never set during view initialization, but it is set right after.

Using the selector string instead returns me a valid jqLite instance but if I try to fetch the controller in ngAfterViewInit or ngAfterViewChecked, the controller is not set.

I am not using ng-if, ng-repeat directives that could delay the execution, but I am using templateUrl for all of my components (but they are already precached in the $templateCache) if this could be a problem. However, I did try switching to standard template and it didn't fix the issue.

In my application, the child component doesn't know about the parent and sits in a separate module and only the parent retrieves an instance the child component. I don't need the forwardRef in this case.

Workaround is to put a 0 $timeout that finishes initialization, but I would like to avoid having to resort to this.

Any ideas ? 

I am using ng-metadata 2.1.1.

**Comment by Hotell** [comment]
can you provide a plunk pls? https://plnkr.co/edit/7Fr7oO

**note about templateUrl:**

- using it can become PITA, because even when you provide the template in `$templateCache` it loads it async in next tick, so I highly recommend to always use `template`

**Comment by hspier** [comment]
Turns out it was because of templateUrl vs template. Parent component was changed to template, but not child and as soon as I switched child component from templateUrl to template it started working.

Thanks for the hint about the extra tick with templateUrl even when in cache !

**Comment by giordy** [comment]
What are the options if I'm forced to use templateUrl?
Can @ViewChild be made to work? Right now the value is always undefined.
