### ISSUE TITLE
bundler.d.ts and utils.d.ts missing Type import from facade/lang

### ISSUE THREAD

**Issue by phantom2005** [ngParty/ng-metadata#170]
I found an issue when compiling my typescript using ng-metadata:
- https://github.com/ngParty/ng-metadata/blob/master/src/testing/utils.ts
- https://github.com/ngParty/ng-metadata/blob/master/src/core/util/bundler.ts

Both files are using "Type" which is not recognized when compiling.
After adding 

> import { Type } from '../facade/lang';

to utils.ts and adding 

> import { Type } from '../../facade/lang';

 to bundler.ts the typescript compiles perfectly.

**Comment by DaSchTour** [comment]
Take a look at this ;) #165

**Comment by Hotell** [comment]
issue is that `Type` is defined as global in source and the global defs are getting imported during build, so it's a mistery for me why it doesn't work, I'm using it at angular scaffold and have no TS issues

**Comment by DaSchTour** [comment]
I guess it depends on how TypeScript compiler is configured. If you take all ts files it might work. If you just include your main.ts and rely on TypeScript follow the imports it doesn't exist. So you need to specifically include the global defs of ng-metadata.

**Comment by Hotell** [comment]
yeah that's possible. I would be really thankful if you guys cane simulate that error for me on our angular scaffold so I can properly test the issue and fixed it.
just fork this https://github.com/ngParty/Angular1-scaffold and paste me here the reproduction of the issue.

Thanks !

**Comment by Hotell** [comment]
yeah @DaSchTour , speaking of which can you at least share your `tsconfig` guys? thx

**Comment by phantom2005** [comment]
Mine is configured as follows:
{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "noImplicitReturns": true,
    "outDir": "./Modules",
    "types": [
      "angular",
      "angular-material",
      "angular-mocks",
      "angular-route",
      "chai",
      "core-js",
      "jasmine",
      "jquery",
      "node"
    ],
    "typeRoots": [ "./node_modules/@types" ]
  },
  "exclude": [
    "node_modules",
    "Modules",
    "modules",
    "Scripts",
    "scripts",
    "typings", // <= added workaround to my proj for this issue
    "Obj", // <= asp.net
    "obj"// <= asp.net
  ]
}

**Comment by vwochnik** [comment]
I am having this issue with 3.0.2. Is there any fast workaround that does not require me to change any of the dependency files?

**Comment by phantom2005** [comment]
Yea there is a workout. Open lang.ts en copy the Type implementation of Function.
Remove "export" and create your own .d.ts file and add it as "// reference" to your TypeScript.

**Comment by Hotell** [comment]
new version is out, pls try if this is still an issue, if yes, I will re-open this. huh, sorry for any inconvenience guys

**Comment by vwochnik** [comment]
Wow! Many thanks! It is working fine now.

**Comment by Hotell** [comment]
glad to hear that! sorry for trouble folks and that it took so long. cheers!

**Comment by vwochnik** [comment]
For some reason, the npm package only contains `*.d.ts` and `*.js` files but the `*.ts` files from the repository are missing.

**Comment by aciccarello** [comment]
@vwochnik That is how they are released to npm. The source files aren't needed because they are compiled before they are published. This helps make installing the project faster by avoiding compiling or shipping source files.

**Comment by vwochnik** [comment]
But shipping source files does not make the package much bigger. It's common practice so developers like me do have the option to compile if they choose to. The `*.js` file shipped are using CommonJS from my observing and I choose to use a different format. Hence I want to compile the source files and I am wondering why they are missing. This choice does not offer much advantage IMO.
