### ISSUE TITLE
Directive @HostListener and preventing input doesn't work

### ISSUE THREAD

**Issue by phantom2005** [ngParty/ng-metadata#171]
https://plnkr.co/edit/eWadyPkdpyXyuLt9YyjC?p=info

Currently @HostListener is not able to prevent input.
@Hotell mentioned this was an Angular issue not a ng-metadata issue.

> @Directive({ selector: "[test-directive]" })
> export class TestDirective {
>     @HostListener("keydown", ["$event"])
>     onKeyDown(e: KeyboardEvent): boolean {
>       console.log(e);
>         e.preventDefault();
>         e.stopPropagation();
>         return false;
>     }
> }

**Comment by Hotell** [comment]
![host-listener-ng-metadata-issue](https://cloud.githubusercontent.com/assets/1223799/19925986/935feee8-a0f2-11e6-95bc-c86c11289db6.gif)

**Comment by Hotell** [comment]
the problem is, that the hostListener callback is called within $applyAsync so it can keep up with angular digest cycle. That is the reason why it's already too late to preventDefault because that event occurred in the browser, but it gets to angular in next tick

**Comment by Hotell** [comment]
it works in Angular 2, http://plnkr.co/edit/Filt11A5y6hUd06o39jh?p=preview
