### ISSUE TITLE
update hybrid ng1/ng2 app recipe

### ISSUE THREAD

**Issue by Hotell** [ngParty/ng-metadata#176]
Very important thing are missing in hybrid app docs:
- when downgrading ng2 entities they need to be also registered via ng2 NgModule
- reference to official guide https://angular.io/docs/ts/latest/guide/upgrade.html#!#using-angular-2-components-from-angular-1-code

**Comment by JamesHenry** [comment]
Yeah, they just changed all of this in Angular 2.2.0...
