### ISSUE TITLE
is it save to use rxjs@5.0.0-rc.5?

### ISSUE THREAD

**Issue by david-gang** [ngParty/ng-metadata#185]
In the documentation it is written that we should 
> npm i --save rxjs@5.0.0-rc.1

Is it safe to use a later version ?

**Comment by Hotell** [comment]
I thinks yes, Rx is used only for EventEmitter, but we are following angular 2 dependencies, so we will mirror what version they have as peerDependency

**Comment by DaSchTour** [comment]
Maybe we could even jump to `^5.0.1` or `~5.0.1`?
