### ISSUE TITLE
ngOnInit 1.6 equivalent and supported?

### ISSUE THREAD

**Issue by raDiesle** [ngParty/ng-metadata#193]
Hi,

I see in the examples, that ng-metadata supports ngOnInit, is this correct?
Angular 1.6 introduces $ngInit. 

Is the ngOnInit by ng-metadata equivalent to the $ngInit, 
If not, should we use and onNgInit by ngMetdata ?
`
.config(function($compileProvider) {
  $compileProvider.preAssignBindingsEnabled(true);
})
`

**Comment by aciccarello** [comment]
ng-metadata added support for `ngOnInit` before `$ngInit` was introduced. I'm not sure if they are 100% equivalent but you should use `ngOnInit` to match the Angular 2+ style. It shouldn't need any `$compileProvider` configuration.

**Comment by Hotell** [comment]
Closing this cause it's implemented since day 1 :)
