### ISSUE TITLE
use angular 2 events with ng-metadata

### ISSUE THREAD

**Issue by david-gang** [ngParty/ng-metadata#194]
This is a feature request.
With ng-metadata we can just use the new syntax (my-cool-event) with custom events. It is not possible to write (click) = ''. Instead we have to write 'ng-click'. 

In ng-forward it was possible to do so:
https://github.com/ngUpgraders/ng-forward/blob/master/lib/events/events.ts

It would be cool to have this syntax.

**Comment by aciccarello** [comment]
@david-gang are you suggesting adding aliases for the `ng-*` events? If so, I'd think that's a good idea so long as it can be implement generically for multiple ng-directives and doesn't have major performance implications.

**Comment by Hotell** [comment]
hmm I see potential issue, when running in hybrid mode ( conflict between aliased ng-click => click and angular 2 click )
