### ISSUE TITLE
Doesn't work with @uirouter/angularjs types [TypeScript@2.4.2] [ng-metadata@4.0.1]

### ISSUE THREAD

**Issue by dlq84** [ngParty/ng-metadata#206]
Hi, I hope I'm wrong assuming this project is abandoned? I'm going to report a problem I'm facing anyway.

`@uirouter/angularjs` is written in typescript and therefore it has its own type declarations included in its npm package. So far so good.

The problem I'm facing is with `@Inject('$state')` into the constructor of a Component in this case.

I can without a problem do 

`constructor(@Inject('$state) private $state)`

But when I try to declare it with a type...

```
import { StateService } from '@uirouter/angularjs';
[...]
constructor(@Inject('$state') private $state: IStateService)
```

... it fails with this console output

```
Error: [$compile:ctreq] Controller 'undefined$state', required by directive 'auth', can't be found!
http://errors.angularjs.org/1.6.6/$compile/ctreq?p0=undefined%24state&p1=auth
    at angular.js:116
    at getControllers (angular.js:10015)
    at getControllers (angular.js:10022)
    at nodeLinkFn (angular.js:9915)
    at angular.js:10273
    at processQueue (angular.js:17051)
    at angular.js:17095
    at Scope.$digest (angular.js:18233)
    at Scope.$apply (angular.js:18531)
    at done (angular.js:12547)
```

I'm not sure where the problem starts, but I would guess it starts somewhere in the logic of the Inject-decorator while building the $inject array, i noticed that the string will be name `$state#1` and not `$state` as one would expect... But that seems unlikely since types should be removed, maybe webpack is doing stuff that Inject-decorator is not prepared for?

Anyway, I used ng-annotate-loader (and ng-decorated) before using ng-metadata, and that worked as expected.

I would love to get some pointers from someone who knows what they are doing. And if you want code that replicates the behavior, I can provide that upon request.

Thank you!

**Comment by aciccarello** [comment]
That's odd. Why would the angular compiler care about the type definition? I would suspect that ui-router is trying to instantiate the controller itself somehow. Could you go ahead with putting together some more information? An example repo would be great though I know that takes time.

FYI, with ui-router 0.4.2 I use a template with my component as the state definition. My understanding is that NgMetadata needs to set up the injection in your component declaration.

**Comment by dlq84** [comment]
Thank you for your response.

> That's odd. Why would the angular compiler care about the type definition?

Exactly my thought!

I will put together a repo ASAP, brb.

**Comment by dlq84** [comment]
This is embarrassing, but while creating the test repo for you I noticed this strange compilerOption in my tsconfig.json: `emitDecoratorMetadata: true`, turning that off solved my problem...

The reason that was turned on was that I wanted to have the exact same conf as my other project that are based on Angular2+. 

Anyway, maybe that setting should be supported by `ng-metadata` and you still want me to create the repo?

**Comment by aciccarello** [comment]
So you should have the `emitDecoratorMetadata` option set to true (see the [readme](https://github.com/ngParty/ng-metadata#tsconfigjson)). You are saying that it worked with it off? I think `ng-metadata` needs that metadata at runtime to figure out your component configuration.

**Comment by mtraynham** [comment]
@dlq84 I ran into an issue with TypeScript and UI Router $state injection a while back.  I believe it stems from the fact that UI Router 1.0.6, switched its main script file to one that **doesn't** re-export `@uirouter/core`.

https://github.com/angular-ui/ui-router/issues/3514

Therefore ng-metadata & TypeScript try to annotate the `$state` injected variable, but can't because what you've imported is undefined.

Instead try:
```ts
import { StateService } from '@uirouter/core';
```

**Comment by dlq84** [comment]
@mtraynham Thank you! I just tried your solution and it does in fact work when i switch to to `@uirouter/core`!

@aciccarello I see, I missed that part, with @mtraynham's solution it works now!

Thank you both for your time, I will close this issue now since it seems to work!
