### ISSUE TITLE
Compile Error with @types/angular@1.6.38

### ISSUE THREAD

**Issue by DaSchTour** [ngParty/ng-metadata#213]
`node_modules/ng-metadata/src/core/directives/metadata_directives.d.ts(16,15): error TS2314: Generic type 'IDirectiveCompileFn<TScope>' requires 1 type argument(s).`

**Comment by aciccarello** [comment]
:+1: Probably caused by DefinitelyTyped/DefinitelyTyped#21167

**Comment by aciccarello** [comment]
Even though this was posted first I'll close this as a duplicate of #214 which has a little more info.
