### ISSUE TITLE
tsc error when building locally, conflict with AngularJs typings

### ISSUE THREAD

**Issue by mtraynham** [ngParty/ng-metadata#214]
I've come across this because of a change in a typing from DefinitelyTyped to [AngularJS](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21167) [LN1980](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21167/files#diff-55d580b6c4e35681b6d79448927bd145R1980).  This new typing conflicts with source code presently in [ng-metadata-src/core/directives/metadata-directives](https://github.com/ngParty/ng-metadata/blob/master/src/core/directives/metadata_directives.ts#L16).

```sh
node_modules/ng-metadata/src/core/directives/metadata_directives.d.ts(16,15): error TS2314: Generic type 'IDirectiveCompileFn<TScope>' requires 1 type argument(s).
```

I actually import this module, `ng-metadata/src/core/directives/metadata_directives`, so that I can use those decorator features to [generate a component template](https://github.com/ngParty/ng-metadata/issues/118#issuecomment-311779090).  When two libraries conflict like this, TypeScript hasn't really suggested a good solution for external conflicts [1](https://github.com/Microsoft/TypeScript/issues/8124) .

Although, I could swing a few ways for a solution, I believe the most appropriate resolution is to update this project's typings.

**Comment by aciccarello** [comment]
Thanks for the report. In my mind the scope type should be optional in the angular type definition and not break downstream type usage. 

Updating ng-metadata's types would probably be good but people would have to use `@types/angular@^1.6.38`

**Comment by mtraynham** [comment]
I buy that as well, but does TypeScript support optional generic typings?

**Comment by mtraynham** [comment]
So it does, that PR just didn't do it for all of them...
```ts
    interface IDirectiveCompileFn<TScope extends IScope = IScope> {
```

**Comment by mtraynham** [comment]
For reference: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21278

**Comment by mtraynham** [comment]
Merged up and seems fixed.  So am closing.  Thanks again for the feedback @aciccarello!
