### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by StummeJ** [ngParty/ng-metadata#216]
Hey everyone,

Is there any way to do form validation without having to extend the `IRootScopeService` to include your form name?

**Comment by aciccarello** [comment]
@StummeJ can you explain more how are you trying to do form validation.

**Comment by StummeJ** [comment]
Yes, currently we have a form `<form name="heroForm">`  with an input `<input name="height" requird>` in that form.  We can do validation by extending the `IRootScopeService` by adding our form name as an `any`
```Typescript
interface IHeroScope implements IRootScopeService {
  heroForm: any;
}
```

Then we can check if the form or the input are valid as such
```Typescript
private scope: IHeroScope = [[this is injected]];

if (scope.heroForm.$invalid) {
  [[Invalid form code here]]
}

if (scope.heroForm.height.$invalid) {
  [[Invalid input code here]]
}
```

I really wish there was a better way than to extend scope, and I hope this pseudo example helps out.

**Comment by aciccarello** [comment]
You can use a property on your controller instead via `<form name="$ctrl.heroForm">`. Then you can easily reference it in your component.

```TypeScript
@Component({...})
export class HeroComponent {
  heroForm: IFormController;

  someMethod() {
    if (this.heroForm.$invalid) {...}
  }
}
```

**Comment by Stoom** [comment]
That worked great!  Thanks for the tip.

**Comment by StummeJ** [comment]
@aciccarello Is there a way to support multiple forms?  We have a component with a form including a component with another form.

**Comment by aciccarello** [comment]
@StummeJ I'm not sure what you mean. Do you mean nested forms? AngularJS already supports this. I believe the form becomes a property of the parent form. https://docs.angularjs.org/api/ng/directive/ngForm

**Comment by StummeJ** [comment]
Aah `ng-form` for the win.  Thank you for the help again!
