### ISSUE TITLE
support compile/link function for @Component and @Directive as static method on class

### ISSUE THREAD

**Issue by Hotell** [ngParty/ng-metadata#36]
This will have one constraints, user won't be able to inject anything, just use locals which are:
- raw dom tElement
- tAttrs

It is already available from from within `legacy` property on `@Component/@Directive` decorator, but we should also support it as a static method on class

```typescript
@Directive({selector:'[template-changer]'})
class MyDirective{
  static compile(tElement: ng.IAugmentedJquery, tAttrs: ng.IAttributes){
   // your compile logic
  }
}
```

**Comment by jensvdh** [comment]
Hi, I stumbled upon this while Googling. My legacy codebase heavily relies on accessing services injected into my directives inside their link/compile methods. Is that something that's possible using ng-metadata?
