### ISSUE TITLE
one way data binding by default

### ISSUE THREAD

**Issue by Hotell** [ngParty/ng-metadata#47]
Use one way data binding only and by default as angular 1.5 uses

https://github.com/angular/angular.js/commit/4ac23c0ac59c269d65b7f78efec75d060121bd18#diff-a732922b631efed1b9f33a24082ae0dbL3037

angular doesn't copies those parent values, so if we have object and modify a property it will be mutated on parent, which is not very convenient. We wanna push best practices and stay immutable, so we will copy `@Input` props via `angular.copy`.

Although we should keep fallback for people which really need 2 way binding:

```typescript
// one way only
@Component({ 
  selector: 'hero', 
  template:`hello`
})
class HeroComponent{
  @Input() name: string;
  @Input() skills: string[];
}
```

```typescript
// two-way fallback via alias only
@Component({ 
  selector: 'hero', 
  template:`hello`
})
class HeroComponent{
  @Input('=') name: string;
  @Input('=') skills: string[];
}
```

**Comment by Hotell** [comment]
related #84

**Comment by reppners** [comment]
I think the `angular.copy` for having immutable data should be optional as angular1 and angular2 leave that up to the framework user. While I think its a good thing to support immutable data it should be an option rather than being applied behind the scenes.

Here is a plunker that demonstrates angular2 binding with `ChangeDetectionStrategy.OnPush`
http://embed.plnkr.co/Kuo7pFRqw80dwDEYO4ff/

ng-metadata should by default not have any different behavior.

**Comment by Hotell** [comment]
Hey @reppners ! of course it's already implemented as you've described ;)  this issue is kind of obsolete, and new one is here https://github.com/ngParty/ng-metadata/issues/84

Also check how to use angular.copy like a breeze with ngMetadata and ChangeDetectionStrategy
https://www.youtube.com/watch?v=aUuj-fNyT5w&list=PLc3XlS7BqcAHKQ24Jq5c5YUJNwn_RHl5m&index=2

**Comment by reppners** [comment]
https://plnkr.co/edit/jPgplTehjVaFaUyYp1CG?p=preview

The plunkr demonstrates how angular 2 does not alter the bound object in any way. AFAIK angular 1 also does not alter or copy one-way bound objects.

My use-case/goal:
* instances of classes are coming from a central data-store. Those instances are rxjs observable.
* pass an instance with one-way-binding to a component
* bind it to the view with an async-pipe polyfill or apply manual change detection with the ChangeDetectorRef, whatever suits best to the component.
* have the scope detached so its no performance hit with ChangeDetectionStrategy.OnPush
* refresh the view/scope when the ChangeDetectorRef tells it should

With angular 2 this should be no problem and I was delighted to see that you polyfilled the ChangeDetectorRef and ChangeDetectionStrategy but with the angular.copy in place I can't implement my use-case.

**Comment by Hotell** [comment]
The example is kind of contrived, but I see your point. 

Anyways ( in Angular 2 ) OnPush is meant to be used with Imutables or Observables not with pure JS Objects for reasons you've already mentioned.

By back-porting `ChangeDetectionStrategy` I just wanted to use new ng1 pattern without to much hassle ( cloning `<` bind property within onChange lifecycle hook ) for the user. 

Ng2 change detection is very different beast in comparison with ng1 so the exact "back-port" isn't really possible

I see 2 solutions for your problem:
- don't use `ChangeDetectionStrategy.OnPush` for your use case ( it's really not needed within Angular 1 + ngMetadata if you're using Observables/Imutables as inputs)
- we can do a fix for the binding, so if the binding is an observable/imutable object it will skip angular.copy

wdyt?

**Comment by reppners** [comment]
The primary goal is to have no watches lingering around for values that change seldomly. ng1 does not really provide a way to do this. Its either one-time-bind or having a watch permanently. This is why I wanted to use OnPush. Is this possible or did I misconcept your implementation of ChangeDetectorRef? Being able to temporarily exclude components from the digest and just digesting them when needed would be a huge win for ng1 performance.

Apart from that I think it should be a specific option to do the `angular.copy` because its different in behavior. When somebody takes ng-metadata as a stepping stone to angular 2 then internal behavior suddenly changes.

**Comment by Hotell** [comment]
yes, you can detach scope via back ported ChangeDetectorRef. 
check last example in API docs
https://github.com/ngParty/ng-metadata/blob/master/docs/API.md#changedetectorref

**Comment by Hotell** [comment]
about that angular.copy I agree, but docs are telling the consumer explicitly, how it works and why it works that way https://github.com/ngParty/ng-metadata/blob/master/docs/API.md#changedetectionstrategy , so it's up to the consumer how he uses it. 

Anyway I'm always trying to teach/tell ngMetadata users, that Angular 1 will never be like Angular 2, so one should always read the docs of ng-metadata what's behind the scenes, if in doubt, before using particular "backported" API

**Comment by Hotell** [comment]
So as I see it I will just tweak the OnPush that angular.copy won't be used when binding Immutable/Observable ( it doesn't make much sense anyway, to use OnPush with primitive JS types )

**Comment by reppners** [comment]
What about corner cases where the observable is a property of the bound object? In my case the datastore objects are instances of a class that have a few methods implemented on them which would be lost when applying `angular.copy`. How could those types be detected? 

If this approach is not feasible I guess I stick to not using ChangeDetectionStrategy.OnPush and utilize ChangeDetectorRef to get the behavior I want.

**Comment by Hotell** [comment]
yeah you're right, so in your particular scenario just don't use OnPush and use ChangeDetectorRef.

I will explore possibilities if it's possible to tweak it to be more aligned with Angular 2, but that's not the primary focus right now ( after ngMetadata 2.0  will be released )

Anyway, thanks for brilliant brainstorming ! These kind of conversations are golden!

**Comment by Hotell** [comment]
closed by https://github.com/ngParty/ng-metadata/commit/7aee890639fe8796f4377908b202a94a8a3a9bec
