### ISSUE TITLE
docs and gh-pages

### ISSUE THREAD

**Issue by nickvdyck** [ngParty/ng-metadata#49]
Maybe what this project need is a live (static) site. As landing page for this project and a marketing device for this project. (With marketing device I mean a link to a few nice pages that could be dropped in blog posts, ... :) ) 

I was thinking maybe you could use a gh-pages site to show the api docs, examples, introduction and getting started material, ... 

I'm not sure what your opinion is but wouldn't it be nice to let something like jsdocs generate your api docs. Which could then be picked up by the gh-pages site?

I'm also not sure what your opinion is about how much docs should live in the actual source code.

Anyways I definitely want to help with these things. Just let me know what you think.

**Comment by Hotell** [comment]
Hey mister! 
I'm in Amsterdam on ng-nl, if you are here as well that would be awesome! 

Anyways, yeah that sounds good, but I think we probably should create a git book with docs, like [Dan Abramov's Redux](http://redux.js.org/index.html) book with docs, that would make most sense to me, what do you think?

thanks again for helping ! much appreciated :)

**Comment by nickvdyck** [comment]
Hi,

Sadly I won't I'll need to catch up to the talks via youtube.

Yeah the git books idea sounds good, although I think a gh-pages site and git book are 2 separate things.

Anyways if you would like to take this conversation offline sometime, just let me know.

Happy to help out.

**Comment by Hotell** [comment]
Hey @nickvdyck sure thing, we can chat about things further on slack or so https://ngparty.herokuapp.com/.

I wanted to ask you if you are actively using ngMetadata at work or so, I'm having a webinar tomorrow and I would like to add there who uses it.

Thanks in advance

**Comment by ndcoop** [comment]
Can I suggest http://typedoc.io/?  If you've already heard of it, oh well.  But it is a pretty cool resource to create documentation.

**Comment by Hotell** [comment]
Closed by https://github.com/ngParty/ng-metadata/commit/a2b1dd733b0e313521947c557f18dada909fd40b
