### ISSUE TITLE
docs and quickstart

### ISSUE THREAD

**Issue by dmorosinotto** [ngParty/ng-metadata#59]
What do you think about adding a sample quickstart with related docs guide on how to setup a project to use ngMetadata? 
I was thinking about something like [NG2 5min Quickstart guide](https://angular.io/docs/ts/latest/quickstart.html) with instructions on
- *npm* install + dependency 
- *typings* install 
- setup *systemjs* and *tsconfig* properly config 
to get a simple app up and running with ngMetadata

**Comment by Hotell** [comment]
Hmm I have something like that already in readme https://github.com/ngParty/ng-metadata/blob/master/README.md#installation

**Comment by Hotell** [comment]
But yeah it would be cool to have something more detailed like that, but it will be better suited in a gitbook. I wanna move whole docs there and also this quick intro could be added there. What do you think?

**Comment by dmorosinotto** [comment]
Yes I see the installation section of the readme and I was thinking about expanding this with a subfolder quickstart with a real sample wiredup + a local readme for instruction (installation + other simple walk-trougth guide) something like the playground but not pointing to ngMetadata live code.
 
My idea is to have something like a mini-project that one can extract from the main repo, and use as a starting point. If you think that's not correct to make this all in one place, we can handle it on a separete repo.

About the gitbook right now I don't have an opinion becouse I don't know well the tools an way to port the actual docs into it, but seems to me a big shift and docs refactor work to do... But if you think that this is the right direction we can talk more about this as a separte issue #49

**Comment by Hotell** [comment]
Well mini project for starting dev is here https://github.com/ngParty/Angular1-scaffold

**Comment by dmorosinotto** [comment]
Thanks to point it to me!
Yes it's something like this that I was thinking of, just using SystemJS instead of Webpack and with some more detailed walk-trougth guide.
But you have just covered it in the readme installation section of this repo, so maybe what I'm suggesting is not really needed, or we can simple point the external repo from the docs.

**Comment by Hotell** [comment]
So as agreed during our conversation about this, we will create a GitBook for everything + live code examples via https://gist.run/

**Comment by Hotell** [comment]
closed by https://github.com/ngParty/ng-metadata/commit/a2b1dd733b0e313521947c557f18dada909fd40b
