### ISSUE TITLE
Release 1.6.1 causes issue on $destroy

### ISSUE THREAD

**Issue by JamesHenry** [ngParty/ng-metadata#69]
The commit which fixed `removeWatches` not being called on $destroy https://github.com/ngParty/ng-metadata/commit/cb46729 has actually started causing issues in my app.

The error is:
```TypeError: removeWatchCollection[i] is not a function``` in `removeWatches`

Seems like `_internalWatchers` has one function and one `undefined` in it at that point in my case:
![unspecified-17](https://cloud.githubusercontent.com/assets/900523/14786410/abb0a8ee-0af6-11e6-94b2-0e06e32f4d5c.png)

`removeWatches` is being triggered as a bi-product of a manual scope $destroy that I am doing inside my modal builder.

Could we add a simple guard to ensure that it is a function?

E.g. hacking at the compiled lib:
```
function removeWatches() {
        var removeWatchCollection = _internalWatchers.concat(_internalObservers);
        for (var i = 0, ii = removeWatchCollection.length; i < ii; ++i) {
			if (removeWatchCollection[i] && lang_1.global.angular.isFunction(removeWatchCollection[i])) {
				removeWatchCollection[i]();
			}
        }
    }
```

Happy to submit as a PR

**Comment by Hotell** [comment]
whops, sorry for that ! anyway thx for reporting, and sure, PR are always welcome! cheers

**Comment by Hotell** [comment]
Ping me, if you need guidance in source code, I'm here to help/explain things!

**Comment by JamesHenry** [comment]
No worries: https://github.com/ngParty/ng-metadata/pull/70

**Comment by Hotell** [comment]
Can you just double check smthg for me? This is happening in your use case, on some directive/component, which has defined one or two way binding via `@Input` and you didn't provide it in template? 

Just wanna confirm my theory why this happened in first case. thx

**Comment by JamesHenry** [comment]
Nice catch, yes you are exactly right

**Comment by Hotell** [comment]
perfect, thx!
