### ISSUE TITLE
Readme needs to be updated to typings 1.0

### ISSUE THREAD

**Issue by aciccarello** [ngParty/ng-metadata#94]
With typings 1.0 ambient has been renamed to global. Therefore the suggested commands on the readme should be updated.

> We can now use Typings to install the type definitions for Angular 1
> - npm run typings install jquery -- --save **--ambient**
> - ...

See the [typings readme](https://github.com/typings/typings) for more info.

**Comment by Hotell** [comment]
PR are more than welcome 😉
