### ISSUE TITLE
implement AsyncPipe

### ISSUE THREAD

**Issue by Hotell** [ngParty/ng-metadata#98]
For flawless integration with ngrx/store and Observable services `async` pipe can come handy, so you don't have to manually subscribe to store or Observable 

https://angular.io/docs/ts/latest/api/common/index/AsyncPipe-class.html

**Comment by JamesHenry** [comment]
Just scanning release notes today and thought I would log this before I forget...

They added the ability to provide an onError handler to the async pipe in RC2: https://github.com/angular/angular/pull/7990

I think this will require moving the optional "scope" in your original implementation

**Comment by Hotell** [comment]
thanks for the heads up! will do :)
